### ISSUE TITLE
Using `set_collector(funs = )` in `.onLoad()`

### ISSUE THREAD

**Issue by krlmlr** [cynkra/collector#9]
Seems to work externally, with CRAN dplyr:

``` r
collector::set_collector(pkg = "dplyr", path = ".")
dplyr::mutate(data.frame(a = 1), b = 2)
#>   a b
#> 1 1 2
qs::qread("1-mutate.qs")
#> $call
#> dplyr::mutate(data.frame(a = 1), b = 2)
#> 
#> $env
#> <environment: 0x1171715f8>
#> 
#> $value
#>   a b
#> 1 1 2
```

<sup>Created on 2024-04-18 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

``` r
collector::set_collector(funs = "mutate", pkg = "dplyr", path = ".")
dplyr::mutate(data.frame(a = 1), b = 2)
#>   a b
#> 1 1 2
qs::qread("1-mutate.qs")
#> $call
#> dplyr::mutate(data.frame(a = 1), b = 2)
#> 
#> $env
#> <environment: 0x12dea8fb0>
#> 
#> $value
#>   a b
#> 1 1 2
```

<sup>Created on 2024-04-18 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

But dplyr calls don't seem to be collected after https://github.com/cynkra/dplyr/commit/ab7a247a1002053ae9da46453d9b49fb09a63f65, tested with auk.

**Comment by krlmlr** [comment]
They are not collected because the `set_collector()` call fails. But it doesn't fail terminally because it's run as part of a hook.

I did notice the error message related to `head`, I wonder if it should be more prominent. Should we add a "verbose" mode to `set_collector()` ?

**Comment by moodymudskipper** [comment]
Has it been fixed by other PRS? 

For me this works fine on your collector-6 branch 

```
Sys.setenv(COLLECTOR_PATH = "collector")
devtools::load_all()
#> ℹ Loading dplyr
mutate(data.frame(a = 1), b = 2)
#>   a b
#> 1 1 2
qs::qread("collector/00001-mutate.qs")
#> $call
#> mutate(data.frame(a = 1), b = 2)
#> 
#> $env
#> <environment: 0x112bc33e0>
#> 
#> $value
#>   a b
#> 1 1 2
```

**Comment by krlmlr** [comment]
I had pushed to the f-collector-6 branch to fix. The collection only works partially if there are functions that can't be found in the namespace, such as `head` or `intersect` . The issue remains but should be rephrased to give a better and clearer error message.

**Comment by moodymudskipper** [comment]
Right! got it now.
The default behavior might also be problematic then, because we patch only exported functions, so the `union` methods of dplyr would be ignored.
We have several solutions: 
* patch S3 methods but not the generic
* patch S3 methods if the generic is not in the package
* patch both generics and methods by default

The 3rd might be redundant but :
* We have some logic in generics sometimes, so not completely redundant
* I don't like that the two first options are inconsistent behavior

So I'd prefer to patch by default all exported functions and all S3 methods, what do you think ?

I'll add error handling too

**Comment by moodymudskipper** [comment]
Related, do we want to be able to patch reexports ? these live in the imports env
